const CONTRACT_ADDRESS = '0x5FbDB2315678afecb367f032d93F642f64180aa3';
const LOCAL_NETWORK = "http://127.0.0.1:8545/";
const POLYGON_TEST_NETWORK = "https://rpc-mumbai.maticvigil.com";
const POLYGON_MAIN_NETWORK = "https://polygon-rpc.com/";
const MINIMUM_DEPOSIT = 10;
const MAXIMUM_DEPOSIT = 5000;

export {
  CONTRACT_ADDRESS,
  LOCAL_NETWORK,
  POLYGON_MAIN_NETWORK,
  POLYGON_TEST_NETWORK,
  MINIMUM_DEPOSIT,
  MAXIMUM_DEPOSIT,
}